package com.tasbeeh.app.presentation.localization

import androidx.compose.runtime.compositionLocalOf
import java.util.Locale

data class AppStrings(
    val locale: Locale,
    val isRtl: Boolean,
    // Navigation
    val navCounter: String,
    val navDhikrs: String,
    val navHistory: String,
    val navSettings: String,
    // Counter screen
    val selectDhikr: String,
    val reset: String,
    val save: String,
    // Dhikr list screen
    val dhikrsTitle: String,
    val addDhikr: String,
    val myDhikrs: String,
    val newDhikr: String,
    val dhikrNameLabel: String,
    val dhikrNameRequired: String,
    val arabicTextLabel: String,
    val goalCountLabel: String,
    val add: String,
    val cancel: String,
    val delete: String,
    // History screen
    val historyTitle: String,
    val recordDeleted: String,
    val noRecords: String,
    // Settings screen
    val settingsTitle: String,
    val soundVibrationGroup: String,
    val vibrationTitle: String,
    val vibrationSubtitle: String,
    val clickSoundTitle: String,
    val clickSoundSubtitle: String,
    val appearanceGroup: String,
    val darkThemeTitle: String,
    val darkThemeSubtitle: String,
    val languageGroup: String,
    val langRu: String,
    val langEn: String,
    val langAr: String,
    val dataGroup: String,
    val clearHistory: String,
    val clearHistoryConfirmTitle: String,
    val clearHistoryConfirmBody: String,
    val appVersion: String,
    // Widget
    val widgetOpenApp: String,
    val widgetLabel: String
)

val RussianStrings = AppStrings(
    locale = Locale("ru"),
    isRtl = false,
    navCounter = "Счётчик",
    navDhikrs = "Зикры",
    navHistory = "История",
    navSettings = "Настройки",
    selectDhikr = "Выберите зикр",
    reset = "Сбросить",
    save = "Сохранить",
    dhikrsTitle = "Зикры",
    addDhikr = "Добавить зикр",
    myDhikrs = "Мои зикры",
    newDhikr = "Новый зикр",
    dhikrNameLabel = "Название *",
    dhikrNameRequired = "Название обязательно",
    arabicTextLabel = "Арабский текст",
    goalCountLabel = "Цель (количество)",
    add = "Добавить",
    cancel = "Отмена",
    delete = "Удалить",
    historyTitle = "История",
    recordDeleted = "Запись удалена",
    noRecords = "Пока нет записей",
    settingsTitle = "Настройки",
    soundVibrationGroup = "Звук и вибрация",
    vibrationTitle = "Вибрация",
    vibrationSubtitle = "Вибрировать при нажатии",
    clickSoundTitle = "Звук клика",
    clickSoundSubtitle = "Звук при каждом нажатии",
    appearanceGroup = "Внешний вид",
    darkThemeTitle = "Тёмная тема",
    darkThemeSubtitle = "Включить тёмный режим",
    languageGroup = "Язык",
    langRu = "Русский",
    langEn = "English",
    langAr = "العربية",
    dataGroup = "Данные",
    clearHistory = "Очистить историю",
    clearHistoryConfirmTitle = "Очистить историю?",
    clearHistoryConfirmBody = "Все записи будут удалены. Это действие нельзя отменить.",
    appVersion = "Версия 1.0.0",
    widgetOpenApp = "Открыть",
    widgetLabel = "Тасбех"
)

val EnglishStrings = AppStrings(
    locale = Locale.ENGLISH,
    isRtl = false,
    navCounter = "Counter",
    navDhikrs = "Dhikrs",
    navHistory = "History",
    navSettings = "Settings",
    selectDhikr = "Select dhikr",
    reset = "Reset",
    save = "Save",
    dhikrsTitle = "Dhikrs",
    addDhikr = "Add dhikr",
    myDhikrs = "My dhikrs",
    newDhikr = "New dhikr",
    dhikrNameLabel = "Name *",
    dhikrNameRequired = "Name is required",
    arabicTextLabel = "Arabic text",
    goalCountLabel = "Goal (count)",
    add = "Add",
    cancel = "Cancel",
    delete = "Delete",
    historyTitle = "History",
    recordDeleted = "Record deleted",
    noRecords = "No records yet",
    settingsTitle = "Settings",
    soundVibrationGroup = "Sound & Vibration",
    vibrationTitle = "Vibration",
    vibrationSubtitle = "Vibrate on tap",
    clickSoundTitle = "Click sound",
    clickSoundSubtitle = "Sound on each tap",
    appearanceGroup = "Appearance",
    darkThemeTitle = "Dark theme",
    darkThemeSubtitle = "Enable dark mode",
    languageGroup = "Language",
    langRu = "Русский",
    langEn = "English",
    langAr = "العربية",
    dataGroup = "Data",
    clearHistory = "Clear history",
    clearHistoryConfirmTitle = "Clear history?",
    clearHistoryConfirmBody = "All records will be deleted. This action cannot be undone.",
    appVersion = "Version 1.0.0",
    widgetOpenApp = "Open",
    widgetLabel = "Tasbeeh"
)

val ArabicStrings = AppStrings(
    locale = Locale("ar"),
    isRtl = true,
    navCounter = "العداد",
    navDhikrs = "الأذكار",
    navHistory = "التاريخ",
    navSettings = "الإعدادات",
    selectDhikr = "اختر ذكرًا",
    reset = "إعادة",
    save = "حفظ",
    dhikrsTitle = "الأذكار",
    addDhikr = "إضافة ذكر",
    myDhikrs = "أذكاري",
    newDhikr = "ذكر جديد",
    dhikrNameLabel = "الاسم *",
    dhikrNameRequired = "الاسم مطلوب",
    arabicTextLabel = "النص العربي",
    goalCountLabel = "الهدف (العدد)",
    add = "إضافة",
    cancel = "إلغاء",
    delete = "حذف",
    historyTitle = "التاريخ",
    recordDeleted = "تم الحذف",
    noRecords = "لا توجد سجلات",
    settingsTitle = "الإعدادات",
    soundVibrationGroup = "الصوت والاهتزاز",
    vibrationTitle = "الاهتزاز",
    vibrationSubtitle = "الاهتزاز عند النقر",
    clickSoundTitle = "صوت النقر",
    clickSoundSubtitle = "صوت عند كل نقرة",
    appearanceGroup = "المظهر",
    darkThemeTitle = "الوضع الداكن",
    darkThemeSubtitle = "تفعيل الوضع الداكن",
    languageGroup = "اللغة",
    langRu = "Русский",
    langEn = "English",
    langAr = "العربية",
    dataGroup = "البيانات",
    clearHistory = "مسح التاريخ",
    clearHistoryConfirmTitle = "مسح التاريخ؟",
    clearHistoryConfirmBody = "سيتم حذف جميع السجلات. لا يمكن التراجع عن هذا الإجراء.",
    appVersion = "الإصدار 1.0.0",
    widgetOpenApp = "فتح",
    widgetLabel = "التسبيح"
)

val LocalStrings = compositionLocalOf<AppStrings> { RussianStrings }

fun stringsFor(language: String): AppStrings = when (language) {
    "en" -> EnglishStrings
    "ar" -> ArabicStrings
    else -> RussianStrings
}
