package com.tasbeeh.app.presentation.localization

import androidx.compose.runtime.compositionLocalOf
import com.tasbeeh.app.domain.model.BackgroundTheme
import com.tasbeeh.app.domain.model.Reminder
import com.tasbeeh.app.domain.model.TasbihType
import java.util.Locale

data class AppStrings(
    val locale: Locale,
    val isRtl: Boolean,
    // Navigation
    val navCounter: String,
    val navDhikrs: String,
    val navHistory: String,
    val navSettings: String,
    val navAnalytics: String,
    val navReminder: String,
    // Counter
    val tasbeh: String,
    val selectDhikr: String,
    val reset: String,
    val save: String,
    val dhikrComplete: String,
    val goal: String,
    val back: String,
    val open: String,
    val close: String,
    val today: String,
    // Dhikr list
    val dhikrsTitle: String,
    val addDhikr: String,
    val myDhikrs: String,
    val newDhikr: String,
    val dhikrNameLabel: String,
    val dhikrNameRequired: String,
    val arabicTextLabel: String,
    val goalCountLabel: String,
    val add: String,
    val cancel: String,
    val delete: String,
    val searchPlaceholder: String,
    val duaCategories: List<String>,
    // History
    val historyTitle: String,
    val recordDeleted: String,
    val noRecords: String,
    val completedZikrsHint: String,
    // Analytics
    val analyticsTitle: String,
    val totalZikrs: String,
    val completedSessionsStat: String,
    val weekActivity: String,
    val recentSessions: String,
    val noSessionsYet: String,
    // Settings (legacy unused but kept)
    val soundVibrationGroup: String,
    val vibrationTitle: String,
    val vibrationSubtitle: String,
    val clickSoundTitle: String,
    val clickSoundSubtitle: String,
    val appearanceGroup: String,
    val darkThemeTitle: String,
    val darkThemeSubtitle: String,
    val languageGroup: String,
    val langRu: String,
    val langEn: String,
    val langAr: String,
    val langTj: String,
    val dataGroup: String,
    val clearHistory: String,
    val clearHistoryConfirmTitle: String,
    val clearHistoryConfirmBody: String,
    val appVersion: String,
    // Settings switches
    val autoCountTitle: String,
    val autoCountSubtitle: String,
    val textOnScreenTitle: String,
    val textOnScreenSubtitle: String,
    val privacyModeTitle: String,
    val privacyModeSubtitle: String,
    val smartTouchTitle: String,
    val smartTouchSubtitle: String,
    val autoRepeatTitle: String,
    val autoRepeatSubtitle: String,
    val keepScreenOnTitle: String,
    val keepScreenOnSubtitle: String,
    val dailyGoalTitle: String,
    val dailyGoalSubtitle: String,
    // Settings rows
    val settingsTitle: String,
    val islamicToolsTitle: String,
    val islamicToolsSubtitle: String,
    val backgroundThemeTitle: String,
    val backgroundThemeSubtitle: String,
    val premiumGet: String,
    val premiumSubtitle: String,
    val premiumActive: String,
    val premiumThanks: String,
    val privacyAndTerms: String,
    // Background theme names
    val bgForest: String,
    val bgNight: String,
    val bgDawn: String,
    val bgDesert: String,
    val bgSky: String,
    // Tasbih type picker
    val selectCount: String,
    val enterNumber: String,
    val apply: String,
    val tasbihShort: String,
    val tasbihStandard: String,
    val tasbihFull: String,
    val tasbih100: String,
    val tasbihCustom: String,
    // Reminders
    val remindersTitle: String,
    val noReminders: String,
    val tapPlusToAdd: String,
    val newReminder: String,
    val editReminder: String,
    val reminderTitleLabel: String,
    val time: String,
    val repeatDays: String,
    val noRepeat: String,
    val everyDay: String,
    val dayMon: String,
    val dayTue: String,
    val dayWed: String,
    val dayThu: String,
    val dayFri: String,
    val daySat: String,
    val daySun: String,
    // Islamic Tools
    val namesSearchPlaceholder: String,
    val names99title: String,
    // Widget
    val widgetOpenApp: String,
    val widgetLabel: String
)

// ---------------------------------------------------------------------------
// Russian
// ---------------------------------------------------------------------------

val RussianStrings = AppStrings(
    locale                   = Locale("ru"),
    isRtl                    = false,
    navCounter               = "Тасбех",
    navDhikrs                = "Зикры",
    navHistory               = "История",
    navSettings              = "Настройки",
    navAnalytics             = "Анализ",
    navReminder              = "Напоминание",
    tasbeh                   = "Тасбех",
    selectDhikr              = "Выберите зикр",
    reset                    = "Сбросить",
    save                     = "Сохранить",
    dhikrComplete            = "Зикр завершён!",
    goal                     = "Цель:",
    back                     = "Назад",
    open                     = "Открыть",
    close                    = "Закрыть",
    today                    = "Сег",
    dhikrsTitle              = "Дуа и Зикры",
    addDhikr                 = "Добавить зикр",
    myDhikrs                 = "Мои зикры",
    newDhikr                 = "Новый зикр",
    dhikrNameLabel           = "Название *",
    dhikrNameRequired        = "Название обязательно",
    arabicTextLabel          = "Арабский текст",
    goalCountLabel           = "Цель (количество)",
    add                      = "Добавить",
    cancel                   = "Отмена",
    delete                   = "Удалить",
    searchPlaceholder        = "Поиск дуа или зикра...",
    duaCategories            = listOf(
        "Утренние азкары", "Вечерние азкары", "Тасбих и зикры",
        "Дуа перед и после еды", "Дуа перед сном", "Дуа в намазе",
        "Истигфар и покаяние", "Дуа путешествия", "Повседневные дуа",
        "Смерть и джаназа", "Семья и никах", "Хадж и умра",
        "Общие дуа", "Зикры после намаза", "Дуа из Корана",
        "Дуа дома и в пути", "Дуа защиты", "Дуа при болезни и исцелении",
        "Дуа благодарности"
    ),
    historyTitle             = "История",
    recordDeleted            = "Запись удалена",
    noRecords                = "История пуста",
    completedZikrsHint       = "Завершённые зикры появятся здесь",
    analyticsTitle           = "Анализ",
    totalZikrs               = "Всего зикров",
    completedSessionsStat    = "Завершено сессий",
    weekActivity             = "Активность за неделю",
    recentSessions           = "ПОСЛЕДНИЕ СЕССИИ",
    noSessionsYet            = "Сессий ещё нет.\nПройдите зикр в тасбехе.",
    soundVibrationGroup      = "Звук и вибрация",
    vibrationTitle           = "Вибрация",
    vibrationSubtitle        = "Вибрировать при нажатии",
    clickSoundTitle          = "Звук клика",
    clickSoundSubtitle       = "Звук при каждом нажатии",
    appearanceGroup          = "Внешний вид",
    darkThemeTitle           = "Тёмная тема",
    darkThemeSubtitle        = "Включить тёмный режим",
    languageGroup            = "Язык",
    langRu                   = "Русский",
    langEn                   = "English",
    langAr                   = "العربية",
    langTj                   = "Тоҷикӣ",
    dataGroup                = "Данные",
    clearHistory             = "Очистить историю",
    clearHistoryConfirmTitle = "Очистить историю?",
    clearHistoryConfirmBody  = "Все записи будут удалены. Это действие нельзя отменить.",
    appVersion               = "Версия 1.0.5",
    autoCountTitle           = "Автоматический счет зикра",
    autoCountSubtitle        = "Позволяет автоматически считать зикры при нажатии",
    textOnScreenTitle        = "Текст на экране",
    textOnScreenSubtitle     = "Отображает текст зикра на экране счётчика",
    privacyModeTitle         = "Режим конфиденциальности (Скрыть счетчик)",
    privacyModeSubtitle      = "Скрывает цифры счётчика от посторонних глаз",
    smartTouchTitle          = "Умное касание",
    smartTouchSubtitle       = "Позволяет считать, касаясь любого места экрана",
    autoRepeatTitle          = "Автоповтор",
    autoRepeatSubtitle       = "Автоматически сбрасывает счетчик при достижении цели",
    keepScreenOnTitle        = "Не выключать экран",
    keepScreenOnSubtitle     = "Предотвращает отключение экрана во время зикра",
    dailyGoalTitle           = "Ежедневная цель",
    dailyGoalSubtitle        = "При включении уведомляет о достижении ежедневной цели",
    settingsTitle            = "Настройки",
    islamicToolsTitle        = "Исламские инструменты",
    islamicToolsSubtitle     = "99 имён Аллаха",
    backgroundThemeTitle     = "Тема фона",
    backgroundThemeSubtitle  = "Цветовая тема экрана тасбеха",
    premiumGet               = "Получить Premium",
    premiumSubtitle          = "Без рекламы, все темы, аналитика",
    premiumActive            = "Premium активен ★",
    premiumThanks            = "Спасибо за поддержку!",
    privacyAndTerms          = "Политика конфиденциальности • Условия использования",
    bgForest                 = "Лес",
    bgNight                  = "Ночь",
    bgDawn                   = "Рассвет",
    bgDesert                 = "Пустыня",
    bgSky                    = "Небо",
    selectCount              = "Выберите количество",
    enterNumber              = "Введите число",
    apply                    = "Применить",
    tasbihShort              = "Краткий (33 раза)",
    tasbihStandard           = "Стандарт (66 раз)",
    tasbihFull               = "Полный тасбих (99 раз)",
    tasbih100                = "100 раз",
    tasbihCustom             = "Свой...",
    remindersTitle           = "Напоминания",
    noReminders              = "Напоминаний нет",
    tapPlusToAdd             = "Нажмите + чтобы добавить",
    newReminder              = "Новое напоминание",
    editReminder             = "Изменить напоминание",
    reminderTitleLabel       = "Название",
    time                     = "Время:",
    repeatDays               = "Дни повтора:",
    noRepeat                 = "Без повтора",
    everyDay                 = "Каждый день",
    dayMon                   = "Пн",
    dayTue                   = "Вт",
    dayWed                   = "Ср",
    dayThu                   = "Чт",
    dayFri                   = "Пт",
    daySat                   = "Сб",
    daySun                   = "Вс",
    namesSearchPlaceholder   = "Поиск по имени или значению",
    names99title             = "99 Имён Аллаха",
    widgetOpenApp            = "Открыть",
    widgetLabel              = "Тасбех"
)

// ---------------------------------------------------------------------------
// English
// ---------------------------------------------------------------------------

val EnglishStrings = AppStrings(
    locale                   = Locale.ENGLISH,
    isRtl                    = false,
    navCounter               = "Tasbeeh",
    navDhikrs                = "Dhikrs",
    navHistory               = "History",
    navSettings              = "Settings",
    navAnalytics             = "Analytics",
    navReminder              = "Reminder",
    tasbeh                   = "Tasbeeh",
    selectDhikr              = "Select dhikr",
    reset                    = "Reset",
    save                     = "Save",
    dhikrComplete            = "Dhikr complete!",
    goal                     = "Goal:",
    back                     = "Back",
    open                     = "Open",
    close                    = "Close",
    today                    = "Now",
    dhikrsTitle              = "Dua & Dhikr",
    addDhikr                 = "Add dhikr",
    myDhikrs                 = "My dhikrs",
    newDhikr                 = "New dhikr",
    dhikrNameLabel           = "Name *",
    dhikrNameRequired        = "Name is required",
    arabicTextLabel          = "Arabic text",
    goalCountLabel           = "Goal (count)",
    add                      = "Add",
    cancel                   = "Cancel",
    delete                   = "Delete",
    searchPlaceholder        = "Search dua or dhikr...",
    duaCategories            = listOf(
        "Morning Azkar", "Evening Azkar", "Tasbih & Dhikr",
        "Dua before & after eating", "Dua before sleep", "Dua in prayer",
        "Istighfar & Repentance", "Travel dua", "Everyday dua",
        "Death & Janaza", "Family & Nikah", "Hajj & Umrah",
        "General dua", "Dhikr after prayer", "Dua from Quran",
        "Dua at home & on journey", "Dua for protection", "Dua in illness & healing",
        "Dua of gratitude"
    ),
    historyTitle             = "History",
    recordDeleted            = "Record deleted",
    noRecords                = "History is empty",
    completedZikrsHint       = "Completed dhikrs will appear here",
    analyticsTitle           = "Analytics",
    totalZikrs               = "Total dhikrs",
    completedSessionsStat    = "Sessions done",
    weekActivity             = "Weekly activity",
    recentSessions           = "RECENT SESSIONS",
    noSessionsYet            = "No sessions yet.\nComplete a dhikr in Tasbeeh.",
    soundVibrationGroup      = "Sound & Vibration",
    vibrationTitle           = "Vibration",
    vibrationSubtitle        = "Vibrate on tap",
    clickSoundTitle          = "Click sound",
    clickSoundSubtitle       = "Sound on each tap",
    appearanceGroup          = "Appearance",
    darkThemeTitle           = "Dark theme",
    darkThemeSubtitle        = "Enable dark mode",
    languageGroup            = "Language",
    langRu                   = "Русский",
    langEn                   = "English",
    langAr                   = "العربية",
    langTj                   = "Тоҷикӣ",
    dataGroup                = "Data",
    clearHistory             = "Clear history",
    clearHistoryConfirmTitle = "Clear history?",
    clearHistoryConfirmBody  = "All records will be deleted. This action cannot be undone.",
    appVersion               = "Version 1.0.5",
    autoCountTitle           = "Auto dhikr count",
    autoCountSubtitle        = "Automatically count dhikrs on tap",
    textOnScreenTitle        = "Text on screen",
    textOnScreenSubtitle     = "Show dhikr text on counter screen",
    privacyModeTitle         = "Privacy mode (Hide counter)",
    privacyModeSubtitle      = "Hide counter digits from others",
    smartTouchTitle          = "Smart touch",
    smartTouchSubtitle       = "Count by tapping anywhere on screen",
    autoRepeatTitle          = "Auto repeat",
    autoRepeatSubtitle       = "Automatically reset counter on goal",
    keepScreenOnTitle        = "Keep screen on",
    keepScreenOnSubtitle     = "Prevent screen from turning off during dhikr",
    dailyGoalTitle           = "Daily goal",
    dailyGoalSubtitle        = "Notify when daily goal is reached",
    settingsTitle            = "Settings",
    islamicToolsTitle        = "Islamic Tools",
    islamicToolsSubtitle     = "99 Names of Allah",
    backgroundThemeTitle     = "Background theme",
    backgroundThemeSubtitle  = "Tasbeeh screen color theme",
    premiumGet               = "Get Premium",
    premiumSubtitle          = "No ads, all themes, analytics",
    premiumActive            = "Premium active ★",
    premiumThanks            = "Thank you for your support!",
    privacyAndTerms          = "Privacy Policy • Terms of Use",
    bgForest                 = "Forest",
    bgNight                  = "Night",
    bgDawn                   = "Dawn",
    bgDesert                 = "Desert",
    bgSky                    = "Sky",
    selectCount              = "Select count",
    enterNumber              = "Enter number",
    apply                    = "Apply",
    tasbihShort              = "Short (33 times)",
    tasbihStandard           = "Standard (66 times)",
    tasbihFull               = "Full tasbeeh (99 times)",
    tasbih100                = "100 times",
    tasbihCustom             = "Custom...",
    remindersTitle           = "Reminders",
    noReminders              = "No reminders",
    tapPlusToAdd             = "Tap + to add",
    newReminder              = "New reminder",
    editReminder             = "Edit reminder",
    reminderTitleLabel       = "Title",
    time                     = "Time:",
    repeatDays               = "Repeat days:",
    noRepeat                 = "No repeat",
    everyDay                 = "Every day",
    dayMon                   = "Mon",
    dayTue                   = "Tue",
    dayWed                   = "Wed",
    dayThu                   = "Thu",
    dayFri                   = "Fri",
    daySat                   = "Sat",
    daySun                   = "Sun",
    namesSearchPlaceholder   = "Search by name or meaning",
    names99title             = "99 Names of Allah",
    widgetOpenApp            = "Open",
    widgetLabel              = "Tasbeeh"
)

// ---------------------------------------------------------------------------
// Tajik
// ---------------------------------------------------------------------------

val TajikStrings = AppStrings(
    locale                   = Locale("tg"),
    isRtl                    = false,
    navCounter               = "Тасбеҳ",
    navDhikrs                = "Зикрҳо",
    navHistory               = "Таърих",
    navSettings              = "Танзимот",
    navAnalytics             = "Таҳлил",
    navReminder              = "Ёддошт",
    tasbeh                   = "Тасбеҳ",
    selectDhikr              = "Зикрро интихоб кунед",
    reset                    = "Аз нав",
    save                     = "Нигоҳ доштан",
    dhikrComplete            = "Зикр анҷом ёфт!",
    goal                     = "Ҳадаф:",
    back                     = "Бозгашт",
    open                     = "Кушодан",
    close                    = "Пӯшидан",
    today                    = "Имр",
    dhikrsTitle              = "Дуо ва Зикрҳо",
    addDhikr                 = "Зикр илова кардан",
    myDhikrs                 = "Зикрҳои ман",
    newDhikr                 = "Зикри нав",
    dhikrNameLabel           = "Ном *",
    dhikrNameRequired        = "Ном ҳатмист",
    arabicTextLabel          = "Матни арабӣ",
    goalCountLabel           = "Ҳадаф (шумора)",
    add                      = "Илова",
    cancel                   = "Бекор кардан",
    delete                   = "Нест кардан",
    searchPlaceholder        = "Ҷустуҷӯи дуо ё зикр...",
    duaCategories            = listOf(
        "Азкори субҳ", "Азкори шом", "Тасбеҳ ва зикрҳо",
        "Дуои пеш ва баъди хӯрок", "Дуои пеш аз хоб", "Дуо дар намоз",
        "Истиғфор ва тавба", "Дуои сафар", "Дуоҳои ҳаррӯза",
        "Марг ва ҷаноза", "Оила ва никоҳ", "Ҳаҷ ва умра",
        "Дуоҳои умумӣ", "Зикр баъди намоз", "Дуо аз Қуръон",
        "Дуо дар хона ва сафар", "Дуои ҳифзу амон", "Дуо ҳангоми беморӣ ва шифо",
        "Дуои шукргузорӣ"
    ),
    historyTitle             = "Таърих",
    recordDeleted            = "Сабт нест шуд",
    noRecords                = "Таърих холист",
    completedZikrsHint       = "Зикрҳои анҷомшуда инҷо зоҳир мешаванд",
    analyticsTitle           = "Таҳлил",
    totalZikrs               = "Ҷамъи зикрҳо",
    completedSessionsStat    = "Сессияҳои тамом",
    weekActivity             = "Фаъолияти ҳафтагӣ",
    recentSessions           = "СЕССИЯҲОИ ОХИР",
    noSessionsYet            = "Ҳанӯз сессия нест.\nЗикрро дар тасбеҳ анҷом диҳед.",
    soundVibrationGroup      = "Овоз ва ларза",
    vibrationTitle           = "Ларза",
    vibrationSubtitle        = "Лаг задан ҳангоми пахши тугма",
    clickSoundTitle          = "Овози клик",
    clickSoundSubtitle       = "Овоз ҳангоми ҳар пахш",
    appearanceGroup          = "Зоҳир",
    darkThemeTitle           = "Мавзӯи торик",
    darkThemeSubtitle        = "Ҳолати торикро фаъол кунед",
    languageGroup            = "Забон",
    langRu                   = "Русский",
    langEn                   = "English",
    langAr                   = "العربية",
    langTj                   = "Тоҷикӣ",
    dataGroup                = "Маълумот",
    clearHistory             = "Таърихро тоза кардан",
    clearHistoryConfirmTitle = "Таърих тоза шавад?",
    clearHistoryConfirmBody  = "Ҳамаи сабтҳо нест мешаванд. Ин амалро бозгардонидан мумкин нест.",
    appVersion               = "Версия 1.0.5",
    autoCountTitle           = "Ҳисоби автоматии зикр",
    autoCountSubtitle        = "Ҳангоми пахш ба таври худкор зикр мешуморад",
    textOnScreenTitle        = "Матн дар экран",
    textOnScreenSubtitle     = "Матни зикрро дар экрани ҳисобгар нишон медиҳад",
    privacyModeTitle         = "Ҳолати хусусӣ (Пинҳон кардани ҳисобгар)",
    privacyModeSubtitle      = "Рақамҳои ҳисобгарро аз дигарон пинҳон мекунад",
    smartTouchTitle          = "Ламси ҳушёр",
    smartTouchSubtitle       = "Бо ламс кардани ҳама ҷои экран ҳисоб мекунад",
    autoRepeatTitle          = "Такрори автоматӣ",
    autoRepeatSubtitle       = "Ҳангоми расидан ба ҳадаф ба таври худкор аз нав месанҷад",
    keepScreenOnTitle        = "Экранро хомӯш накун",
    keepScreenOnSubtitle     = "Ҳангоми зикр аз хомӯш шудани экран пешгирӣ мекунад",
    dailyGoalTitle           = "Ҳадафи рӯзона",
    dailyGoalSubtitle        = "Ҳангоми расидан ба ҳадафи рӯзона хабардор мекунад",
    settingsTitle            = "Танзимот",
    islamicToolsTitle        = "Асбобҳои исломӣ",
    islamicToolsSubtitle     = "99 номи Аллоҳ",
    backgroundThemeTitle     = "Мавзӯи замина",
    backgroundThemeSubtitle  = "Мавзӯи ранги экрани тасбеҳ",
    premiumGet               = "Гирифтани Premium",
    premiumSubtitle          = "Бидуни реклама, ҳамаи мавзӯҳо, таҳлил",
    premiumActive            = "Premium фаъол аст ★",
    premiumThanks            = "Ташаккур барои дастгириатон!",
    privacyAndTerms          = "Сиёсати конфиденсиалӣ • Шартҳои истифода",
    bgForest                 = "Ҷангал",
    bgNight                  = "Шаб",
    bgDawn                   = "Субҳ",
    bgDesert                 = "Биёбон",
    bgSky                    = "Осмон",
    selectCount              = "Шуморро интихоб кунед",
    enterNumber              = "Рақам ворид кунед",
    apply                    = "Татбиқ кардан",
    tasbihShort              = "Кӯтоҳ (33 бор)",
    tasbihStandard           = "Стандарт (66 бор)",
    tasbihFull               = "Тасбеҳи пурра (99 бор)",
    tasbih100                = "100 бор",
    tasbihCustom             = "Худ...",
    remindersTitle           = "Ёдоварӣ",
    noReminders              = "Ёдоварӣ нест",
    tapPlusToAdd             = "Барои илова + -ро клик кунед",
    newReminder              = "Ёдоварии нав",
    editReminder             = "Тағйири ёдоварӣ",
    reminderTitleLabel       = "Ном",
    time                     = "Вақт:",
    repeatDays               = "Рӯзҳои такрор:",
    noRepeat                 = "Бидуни такрор",
    everyDay                 = "Ҳар рӯз",
    dayMon                   = "Дш",
    dayTue                   = "Сш",
    dayWed                   = "Чш",
    dayThu                   = "Пш",
    dayFri                   = "Ҷм",
    daySat                   = "Шн",
    daySun                   = "Яш",
    namesSearchPlaceholder   = "Ҷустуҷӯ аз рӯи ном ё маъно",
    names99title             = "99 Номи Аллоҳ",
    widgetOpenApp            = "Кушодан",
    widgetLabel              = "Тасбеҳ"
)

// ---------------------------------------------------------------------------
// Arabic
// ---------------------------------------------------------------------------

val ArabicStrings = AppStrings(
    locale                   = Locale("ar"),
    isRtl                    = true,
    navCounter               = "التسبيح",
    navDhikrs                = "الأذكار",
    navHistory               = "التاريخ",
    navSettings              = "الإعدادات",
    navAnalytics             = "التحليل",
    navReminder              = "التذكير",
    tasbeh                   = "التسبيح",
    selectDhikr              = "اختر ذكرًا",
    reset                    = "إعادة",
    save                     = "حفظ",
    dhikrComplete            = "اكتمل الذكر!",
    goal                     = "الهدف:",
    back                     = "رجوع",
    open                     = "فتح",
    close                    = "إغلاق",
    today                    = "الي",
    dhikrsTitle              = "الأذكار والأدعية",
    addDhikr                 = "إضافة ذكر",
    myDhikrs                 = "أذكاري",
    newDhikr                 = "ذكر جديد",
    dhikrNameLabel           = "الاسم *",
    dhikrNameRequired        = "الاسم مطلوب",
    arabicTextLabel          = "النص العربي",
    goalCountLabel           = "الهدف (العدد)",
    add                      = "إضافة",
    cancel                   = "إلغاء",
    delete                   = "حذف",
    searchPlaceholder        = "بحث في الأدعية والأذكار...",
    duaCategories            = listOf(
        "أذكار الصباح", "أذكار المساء", "التسبيح والأذكار",
        "دعاء قبل وبعد الطعام", "دعاء قبل النوم", "دعاء في الصلاة",
        "الاستغفار والتوبة", "دعاء السفر", "الأدعية اليومية",
        "الموت والجنازة", "الأسرة والنكاح", "الحج والعمرة",
        "الأدعية العامة", "أذكار بعد الصلاة", "أدعية من القرآن",
        "دعاء في البيت والسفر", "دعاء الحماية", "دعاء المرض والشفاء",
        "دعاء الشكر"
    ),
    historyTitle             = "التاريخ",
    recordDeleted            = "تم الحذف",
    noRecords                = "التاريخ فارغ",
    completedZikrsHint       = "ستظهر الأذكار المكتملة هنا",
    analyticsTitle           = "التحليل",
    totalZikrs               = "مجموع الأذكار",
    completedSessionsStat    = "الجلسات المكتملة",
    weekActivity             = "النشاط الأسبوعي",
    recentSessions           = "الجلسات الأخيرة",
    noSessionsYet            = "لا توجد جلسات بعد.\nأكمل ذكرًا في التسبيح.",
    soundVibrationGroup      = "الصوت والاهتزاز",
    vibrationTitle           = "الاهتزاز",
    vibrationSubtitle        = "الاهتزاز عند النقر",
    clickSoundTitle          = "صوت النقر",
    clickSoundSubtitle       = "صوت عند كل نقرة",
    appearanceGroup          = "المظهر",
    darkThemeTitle           = "الوضع الداكن",
    darkThemeSubtitle        = "تفعيل الوضع الداكن",
    languageGroup            = "اللغة",
    langRu                   = "Русский",
    langEn                   = "English",
    langAr                   = "العربية",
    langTj                   = "Тоҷикӣ",
    dataGroup                = "البيانات",
    clearHistory             = "مسح التاريخ",
    clearHistoryConfirmTitle = "مسح التاريخ؟",
    clearHistoryConfirmBody  = "سيتم حذف جميع السجلات. لا يمكن التراجع عن هذا الإجراء.",
    appVersion               = "الإصدار 1.0.5",
    autoCountTitle           = "العد التلقائي للذكر",
    autoCountSubtitle        = "عد الأذكار تلقائيًا عند الضغط",
    textOnScreenTitle        = "النص على الشاشة",
    textOnScreenSubtitle     = "عرض نص الذكر على شاشة العداد",
    privacyModeTitle         = "وضع الخصوصية (إخفاء العداد)",
    privacyModeSubtitle      = "إخفاء أرقام العداد عن الآخرين",
    smartTouchTitle          = "اللمس الذكي",
    smartTouchSubtitle       = "العد بلمس أي مكان على الشاشة",
    autoRepeatTitle          = "التكرار التلقائي",
    autoRepeatSubtitle       = "إعادة تعيين العداد تلقائيًا عند الوصول للهدف",
    keepScreenOnTitle        = "إبقاء الشاشة نشطة",
    keepScreenOnSubtitle     = "منع إيقاف الشاشة أثناء الذكر",
    dailyGoalTitle           = "الهدف اليومي",
    dailyGoalSubtitle        = "إشعار عند الوصول للهدف اليومي",
    settingsTitle            = "الإعدادات",
    islamicToolsTitle        = "الأدوات الإسلامية",
    islamicToolsSubtitle     = "٩٩ اسمًا لله",
    backgroundThemeTitle     = "سمة الخلفية",
    backgroundThemeSubtitle  = "سمة ألوان شاشة التسبيح",
    premiumGet               = "احصل على Premium",
    premiumSubtitle          = "بلا إعلانات، جميع السمات، التحليل",
    premiumActive            = "Premium نشط ★",
    premiumThanks            = "شكرًا لدعمك!",
    privacyAndTerms          = "سياسة الخصوصية • شروط الاستخدام",
    bgForest                 = "الغابة",
    bgNight                  = "الليل",
    bgDawn                   = "الفجر",
    bgDesert                 = "الصحراء",
    bgSky                    = "السماء",
    selectCount              = "اختر العدد",
    enterNumber              = "أدخل الرقم",
    apply                    = "تطبيق",
    tasbihShort              = "قصير (٣٣ مرة)",
    tasbihStandard           = "معياري (٦٦ مرة)",
    tasbihFull               = "تسبيح كامل (٩٩ مرة)",
    tasbih100                = "١٠٠ مرة",
    tasbihCustom             = "مخصص...",
    remindersTitle           = "التذكيرات",
    noReminders              = "لا توجد تذكيرات",
    tapPlusToAdd             = "اضغط + للإضافة",
    newReminder              = "تذكير جديد",
    editReminder             = "تعديل التذكير",
    reminderTitleLabel       = "العنوان",
    time                     = "الوقت:",
    repeatDays               = "أيام التكرار:",
    noRepeat                 = "بلا تكرار",
    everyDay                 = "كل يوم",
    dayMon                   = "إث",
    dayTue                   = "ثل",
    dayWed                   = "أر",
    dayThu                   = "خم",
    dayFri                   = "جم",
    daySat                   = "سب",
    daySun                   = "أح",
    namesSearchPlaceholder   = "البحث بالاسم أو المعنى",
    names99title             = "٩٩ اسمًا لله",
    widgetOpenApp            = "فتح",
    widgetLabel              = "التسبيح"
)

// ---------------------------------------------------------------------------
// Composition local + router
// ---------------------------------------------------------------------------

val LocalStrings = compositionLocalOf<AppStrings> { RussianStrings }

fun stringsFor(language: String): AppStrings = when (language) {
    "en" -> EnglishStrings
    "ar" -> ArabicStrings
    "tg" -> TajikStrings
    else -> RussianStrings
}

// ---------------------------------------------------------------------------
// Presentation-layer extensions that need AppStrings
// ---------------------------------------------------------------------------

fun Reminder.localizedDaysLabel(strings: AppStrings): String {
    val days = daysOfWeek.split(",").mapNotNull { it.trim().toIntOrNull() }
    if (days.isEmpty()) return strings.noRepeat
    if (days.size == 7) return strings.everyDay
    val names = mapOf(
        1 to strings.dayMon, 2 to strings.dayTue, 3 to strings.dayWed,
        4 to strings.dayThu, 5 to strings.dayFri, 6 to strings.daySat, 7 to strings.daySun
    )
    return days.mapNotNull { names[it] }.joinToString(", ")
}

fun TasbihType.localizedName(strings: AppStrings): String = when (id) {
    1    -> strings.tasbihShort
    2    -> strings.tasbihStandard
    3    -> strings.tasbihFull
    4    -> strings.tasbih100
    else -> strings.tasbihCustom
}

fun BackgroundTheme.localizedName(strings: AppStrings): String = when (id) {
    0    -> strings.bgForest
    1    -> strings.bgNight
    2    -> strings.bgDawn
    3    -> strings.bgDesert
    else -> strings.bgSky
}
