package com.tasbeeh.app.domain.model

data class AllahName(
    val number: Int,
    val arabic: String,
    val transliteration: String,
    val meaningRu: String
)

val NinetynineNames = listOf(
    AllahName(1,  "ٱللَّٰه",        "Allah",          "Аллах"),
    AllahName(2,  "ٱلرَّحْمَٰن",    "Ar-Rahman",      "Милостивый"),
    AllahName(3,  "ٱلرَّحِيم",      "Ar-Rahim",       "Милосердный"),
    AllahName(4,  "ٱلْمَلِك",       "Al-Malik",       "Властелин"),
    AllahName(5,  "ٱلْقُدُّوس",     "Al-Quddus",      "Пресвятой"),
    AllahName(6,  "ٱلسَّلَام",      "As-Salam",       "Мир"),
    AllahName(7,  "ٱلْمُؤْمِن",     "Al-Mu'min",      "Верующий (дарующий веру)"),
    AllahName(8,  "ٱلْمُهَيْمِن",   "Al-Muhaymin",    "Хранитель"),
    AllahName(9,  "ٱلْعَزِيز",      "Al-Aziz",        "Могущественный"),
    AllahName(10, "ٱلْجَبَّار",     "Al-Jabbar",      "Всеправящий"),
    AllahName(11, "ٱلْمُتَكَبِّر",  "Al-Mutakabbir",  "Превозвышенный"),
    AllahName(12, "ٱلْخَالِق",      "Al-Khaliq",      "Создатель"),
    AllahName(13, "ٱلْبَارِئ",      "Al-Bari",        "Творец"),
    AllahName(14, "ٱلْمُصَوِّر",    "Al-Musawwir",    "Формообразователь"),
    AllahName(15, "ٱلْغَفَّار",     "Al-Ghaffar",     "Всепрощающий"),
    AllahName(16, "ٱلْقَهَّار",     "Al-Qahhar",      "Всеподавляющий"),
    AllahName(17, "ٱلْوَهَّاب",     "Al-Wahhab",      "Щедрый дарователь"),
    AllahName(18, "ٱلرَّزَّاق",     "Ar-Razzaq",      "Наделяющий уделом"),
    AllahName(19, "ٱلْفَتَّاح",     "Al-Fattah",      "Открывающий"),
    AllahName(20, "ٱلْعَلِيم",      "Al-Alim",        "Всезнающий"),
    AllahName(21, "ٱلْقَابِض",      "Al-Qabid",       "Сжимающий"),
    AllahName(22, "ٱلْبَاسِط",      "Al-Basit",       "Расширяющий"),
    AllahName(23, "ٱلْخَافِض",      "Al-Khafid",      "Унижающий"),
    AllahName(24, "ٱلرَّافِع",      "Ar-Rafi",        "Возвышающий"),
    AllahName(25, "ٱلْمُعِزّ",      "Al-Mu'izz",      "Прославляющий"),
    AllahName(26, "ٱلْمُذِلّ",      "Al-Muzill",      "Унижающий"),
    AllahName(27, "ٱلسَّمِيع",      "As-Sami",        "Всеслышащий"),
    AllahName(28, "ٱلْبَصِير",      "Al-Basir",       "Всевидящий"),
    AllahName(29, "ٱلْحَكَم",       "Al-Hakam",       "Судья"),
    AllahName(30, "ٱلْعَدْل",       "Al-Adl",         "Справедливый"),
    AllahName(31, "ٱللَّطِيف",      "Al-Latif",       "Добросердечный"),
    AllahName(32, "ٱلْخَبِير",      "Al-Khabir",      "Осведомлённый"),
    AllahName(33, "ٱلْحَلِيم",      "Al-Halim",       "Терпеливый"),
    AllahName(34, "ٱلْعَظِيم",      "Al-Azim",        "Величайший"),
    AllahName(35, "ٱلْغَفُور",      "Al-Ghafur",      "Прощающий"),
    AllahName(36, "ٱلشَّكُور",      "Ash-Shakur",     "Благодарный"),
    AllahName(37, "ٱلْعَلِيّ",      "Al-Ali",         "Высочайший"),
    AllahName(38, "ٱلْكَبِير",      "Al-Kabir",       "Великий"),
    AllahName(39, "ٱلْحَفِيظ",      "Al-Hafiz",       "Хранитель"),
    AllahName(40, "ٱلْمُقِيت",      "Al-Muqit",       "Питающий"),
    AllahName(41, "ٱلْحَسِيب",      "Al-Hasib",       "Вычислитель"),
    AllahName(42, "ٱلْجَلِيل",      "Al-Jalil",       "Величественный"),
    AllahName(43, "ٱلْكَرِيم",      "Al-Karim",       "Щедрый"),
    AllahName(44, "ٱلرَّقِيب",      "Ar-Raqib",       "Бдительный"),
    AllahName(45, "ٱلْمُجِيب",      "Al-Mujib",       "Отвечающий"),
    AllahName(46, "ٱلْوَاسِع",      "Al-Wasi",        "Необъятный"),
    AllahName(47, "ٱلْحَكِيم",      "Al-Hakim",       "Мудрый"),
    AllahName(48, "ٱلْوَدُود",      "Al-Wadud",       "Любящий"),
    AllahName(49, "ٱلْمَجِيد",      "Al-Majid",       "Преславный"),
    AllahName(50, "ٱلْبَاعِث",      "Al-Ba'ith",      "Воскрешающий"),
    AllahName(51, "ٱلشَّهِيد",      "Ash-Shahid",     "Свидетель"),
    AllahName(52, "ٱلْحَقّ",        "Al-Haqq",        "Истинный"),
    AllahName(53, "ٱلْوَكِيل",      "Al-Wakil",       "Попечитель"),
    AllahName(54, "ٱلْقَوِيّ",      "Al-Qawiyy",      "Сильный"),
    AllahName(55, "ٱلْمَتِين",      "Al-Matin",       "Стойкий"),
    AllahName(56, "ٱلْوَلِيّ",      "Al-Waliyy",      "Покровитель"),
    AllahName(57, "ٱلْحَمِيد",      "Al-Hamid",       "Достохвальный"),
    AllahName(58, "ٱلْمُحْصِي",     "Al-Muhsi",       "Исчисляющий"),
    AllahName(59, "ٱلْمُبْدِئ",     "Al-Mubdi",       "Создающий изначально"),
    AllahName(60, "ٱلْمُعِيد",      "Al-Mu'id",       "Воссоздающий"),
    AllahName(61, "ٱلْمُحْيِي",     "Al-Muhyi",       "Оживляющий"),
    AllahName(62, "ٱلْمُمِيت",      "Al-Mumit",       "Умерщвляющий"),
    AllahName(63, "ٱلْحَيّ",        "Al-Hayy",        "Живой"),
    AllahName(64, "ٱلْقَيُّوم",     "Al-Qayyum",      "Вечно сущий"),
    AllahName(65, "ٱلْوَاجِد",      "Al-Wajid",       "Находящий"),
    AllahName(66, "ٱلْمَاجِد",      "Al-Majid",       "Великодушный"),
    AllahName(67, "ٱلْوَاحِد",      "Al-Wahid",       "Единственный"),
    AllahName(68, "ٱلْأَحَد",       "Al-Ahad",        "Единый"),
    AllahName(69, "ٱلصَّمَد",       "As-Samad",       "Самодостаточный"),
    AllahName(70, "ٱلْقَادِر",      "Al-Qadir",       "Всемогущий"),
    AllahName(71, "ٱلْمُقْتَدِر",   "Al-Muqtadir",    "Обладающий силой"),
    AllahName(72, "ٱلْمُقَدِّم",    "Al-Muqaddim",    "Выдвигающий вперёд"),
    AllahName(73, "ٱلْمُؤَخِّر",    "Al-Mu'akhkhir",  "Откладывающий"),
    AllahName(74, "ٱلْأَوَّل",      "Al-Awwal",       "Первый"),
    AllahName(75, "ٱلْآخِر",        "Al-Akhir",       "Последний"),
    AllahName(76, "ٱلظَّاهِر",      "Az-Zahir",       "Явный"),
    AllahName(77, "ٱلْبَاطِن",      "Al-Batin",       "Скрытый"),
    AllahName(78, "ٱلْوَالِي",      "Al-Wali",        "Управляющий"),
    AllahName(79, "ٱلْمُتَعَالِ",   "Al-Muta'ali",    "Превознесённый"),
    AllahName(80, "ٱلْبَرّ",        "Al-Barr",        "Источник благ"),
    AllahName(81, "ٱلتَّوَّاب",     "At-Tawwab",      "Принимающий покаяние"),
    AllahName(82, "ٱلْمُنْتَقِم",   "Al-Muntaqim",    "Мститель"),
    AllahName(83, "ٱلْعَفُوّ",      "Al-Afuww",       "Прощающий"),
    AllahName(84, "ٱلرَّءُوف",      "Ar-Ra'uf",       "Сострадательный"),
    AllahName(85, "مَالِكُ ٱلْمُلْك","Malik al-Mulk",  "Владелец Царства"),
    AllahName(86, "ذُو ٱلْجَلَال",  "Dhul-Jalal",     "Обладатель Величия"),
    AllahName(87, "ٱلْمُقْسِط",     "Al-Muqsit",      "Справедливый"),
    AllahName(88, "ٱلْجَامِع",      "Al-Jami",        "Собирающий"),
    AllahName(89, "ٱلْغَنِيّ",      "Al-Ghani",       "Богатый"),
    AllahName(90, "ٱلْمُغْنِي",     "Al-Mughni",      "Обогащающий"),
    AllahName(91, "ٱلْمَانِع",      "Al-Mani",        "Препятствующий"),
    AllahName(92, "ٱلضَّارّ",       "Ad-Darr",        "Причиняющий вред"),
    AllahName(93, "ٱلنَّافِع",      "An-Nafi",        "Приносящий пользу"),
    AllahName(94, "ٱلنُّور",        "An-Nur",         "Свет"),
    AllahName(95, "ٱلْهَادِي",      "Al-Hadi",        "Ведущий правым путём"),
    AllahName(96, "ٱلْبَدِيع",      "Al-Badi",        "Несравненный творец"),
    AllahName(97, "ٱلْبَاقِي",      "Al-Baqi",        "Вечный"),
    AllahName(98, "ٱلْوَارِث",      "Al-Warith",      "Наследник"),
    AllahName(99, "ٱلرَّشِيد",      "Ar-Rashid",      "Ведущий к истине"),
)

data class PrayerTime(
    val name: String,
    val time: String
)
